import type { MetadataRoute } from "next";
import { CANONICAL_SENTENCE, SITE_NAME, SITE_TAGLINE } from "@/lib/site";

// PWA manifest, served at /manifest.webmanifest and linked from the root
// layout. The mark's near-black tile (#0a0a0a) is the splash/app theme; the
// in-browser theme-color (the mobile URL bar) tracks the page background
// instead and is set per color-scheme in layout.tsx's viewport export. Icons
// all derive from the canonical mark (public/icon-*.png, generated by
// scripts/generate-brand-assets.py).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME}, ${SITE_TAGLINE}`,
    short_name: SITE_NAME,
    description: CANONICAL_SENTENCE,
    start_url: "/",
    display: "standalone",
    background_color: "#0a0a0a",
    theme_color: "#0a0a0a",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
